// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4oBAIScRRf0EUzpyp9fz87keFB35r3-I',
    appId: '1:209674836764:web:cee7a7e7dc915ba6ed78d9',
    messagingSenderId: '209674836764',
    projectId: 'gaamhaul',
    authDomain: 'gaamhaul.firebaseapp.com',
    storageBucket: 'gaamhaul.firebasestorage.app',
    measurementId: 'G-KJ5SWTQF17',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpA-lSoGYgaHDOGaCnrYaNHgkWBVSokJo',
    appId: '1:209674836764:android:11c35158acfaa953ed78d9',
    messagingSenderId: '209674836764',
    projectId: 'gaamhaul',
    storageBucket: 'gaamhaul.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNPsW5gp-f0EETkiJ3KJL6w0tpk8q_vpQ',
    appId: '1:209674836764:ios:09bd289aea4e2988ed78d9',
    messagingSenderId: '209674836764',
    projectId: 'gaamhaul',
    storageBucket: 'gaamhaul.firebasestorage.app',
    iosBundleId: 'com.gaamhaul.customerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNPsW5gp-f0EETkiJ3KJL6w0tpk8q_vpQ',
    appId: '1:209674836764:ios:09bd289aea4e2988ed78d9',
    messagingSenderId: '209674836764',
    projectId: 'gaamhaul',
    storageBucket: 'gaamhaul.firebasestorage.app',
    iosBundleId: 'com.gaamhaul.customerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4oBAIScRRf0EUzpyp9fz87keFB35r3-I',
    appId: '1:209674836764:web:bfa799e618f9baaaed78d9',
    messagingSenderId: '209674836764',
    projectId: 'gaamhaul',
    authDomain: 'gaamhaul.firebaseapp.com',
    storageBucket: 'gaamhaul.firebasestorage.app',
    measurementId: 'G-8GSTPF7QEM',
  );
}
